propagation: Fix debug build
Missing c stdio header, fixes:
/home/attems/src/nurqmd/src/propagation.cc:29:68: error: ‘printf’ was not declared in this scope

Signed-off-by: maximilian attems <attems@fias.uni-frankfurt.de>